name: Update Code

on:
  push:
    branches:
      - main

jobs:
  update-code:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH and Git
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client git
          
      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          AWS_CONTAINER_IP: ${{ secrets.AWS_CONTAINER_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H "$AWS_CONTAINER_IP" >> ~/.ssh/known_hosts
          
      - name: Pull Latest Code on Remote AWS Container and Redeploy App
        env:
          AWS_CONTAINER_IP: ${{ secrets.AWS_CONTAINER_IP }}
          AWS_USER: ${{ secrets.AWS_USER }}
        run: |
          ssh "$AWS_USER@$AWS_CONTAINER_IP" "cd ~/htdocs/projects/pegasus-parking && git pull origin main"
